Update holograms on PlotChangeOwnerEvent correct.
IntellectualSites/HoloPlots pull request #109
Opened 2022-10-08 22:46 UTC by BlockyTheDev

## Overview

Fixes #43 

## Description

## Submitter Checklist

- [ ] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [ ] Ensure that the pull request title represents the desired changelog entry.
- [ ] New public fields and methods are annotated with `@since TODO`.
- [ ] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

2022-10-09 17:25 UTC, SirYwell commented
I'd assume this call https://github.com/IntellectualSites/HoloPlots/blob/127dc892d1b650d6f3d27295bb60bbdb583b6bac/src/main/java/com/plotsquared/holoplots/PSHoloUtil.java#L115
to already prevent the issue from happening in the first place, do you know why that isn't the case?

2022-10-09 20:20 UTC, BlockyTheDev commented
> I'd assume this call
> 
> https://github.com/IntellectualSites/HoloPlots/blob/127dc892d1b650d6f3d27295bb60bbdb583b6bac/src/main/java/com/plotsquared/holoplots/PSHoloUtil.java#L115
> 
> 
> to already prevent the issue from happening in the first place, do you know why that isn't the case?

Was that the way you thaught or did you mean, that the code in the updatePlayer method should be changed?

2022-10-09 20:31 UTC, BlockyTheDev commented
Ohh, I should have looked into the method updatePlayer. As far as I see it should handle the "replacement" of the lines, which is not working right, too. Is that right? If yes, I will look into that method when I find time in the next days.

2022-10-09 21:43 UTC, BlockyTheDev commented
I found out why the updatePlayer methode isn't working in the way it should. I will investigate that when I have time in the next days.

2022-10-10 15:42 UTC, BlockyTheDev commented
Now it is removing the HoloPlotID key completely from the HashMap. I also added an information comment, why this way is selected.

2022-10-10 16:16 UTC, SirYwell requested changes
One minor nitpick, but looks good otherwise.

2022-10-10 16:16 UTC, SirYwell commented on src/main/java/com/plotsquared/holoplots/PSHoloUtil.java
> +        // Info: The problem with just calling updatePlayer() is that the old owner UUID is unknown to that methode,
```suggestion
        // Info: The problem with just calling updatePlayer() is that the old owner UUID is unknown to that method,
```

2022-10-10 17:30 UTC, SirYwell approved these changes
Looks good, thanks.

2022-10-23 18:03 UTC, PierreSchwang approved these changes
Looks reasonable

2022-10-23 19:23 UTC, NotMyFault approved these changes

2022-10-23 19:25 UTC, merged