Cleanup Code & support DecentHolograms
IntellectualSites/HoloPlots pull request #118
Opened 2023-01-03 22:19 UTC by PierreSchwang

## Overview
Fixes #48

## Description

### Code Cleanups
- Remove usage of protocollib - we don't need to spawn individual holograms for each player if we use the Console as the LocaleHolder
- Remove interface for IHoloUtil - there is only one implementation
- Get rid of singleton accessors

### Bugfixes
- Fixes pending holograms on unlink & merge
- Get plot owner using PlayerManager, which utilizes the UUID pipeline (Owner does not neccessarly need to exists in server files and is therefor not present as an OfflinePlayer)
- Don't validate plot boundaries (https://github.com/IntellectualSites/HoloPlots/blob/main/src/main/java/com/plotsquared/holoplots/PSHoloUtil.java#L75) anymore.
  - We take every plot which is connected in any means to the chunk.
  - Fixes an issue where only the sign is exactly in another chunk

### New features
- Multiple providers are now supported
  - New Provider: DecentHolograms

This PR does need quite a bit of testing, especially with multiple accounts - I only have one at the moment (thanks Microsoft).
The core of the plugin has changed fundamentally - so if anything is unclear, I'll glad to explain.

## Submitter Checklist

- [x] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [x] Ensure that the pull request title represents the desired changelog entry.
- [ ] New public fields and methods are annotated with `@since TODO`.
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

2023-01-08 08:55 UTC, SirYwell requested changes
A few minor things, but looks good overall.

2023-01-08 08:55 UTC, SirYwell commented on src/main/java/com/plotsquared/holoplots/HoloPlotsPlugin.java
> +            "DecentHolograms", DecentHologramsProvider::new
These Strings are currently duplicated, Can we move them to their corresponding classes as constants?

2023-01-08 08:55 UTC, SirYwell commented on src/main/java/com/plotsquared/holoplots/provider/IHologramProvider.java
> +public interface IHologramProvider {
I'd drop the `I` prefix, I don't know why it was used in this project before.

2023-01-08 14:38 UTC, SirYwell approved these changes

2023-01-08 16:07 UTC, NotMyFault approved these changes

2023-01-08 16:14 UTC, NotMyFault commented
![Screenshot 2023-01-08 at 17 13 51](https://user-images.githubusercontent.com/13383509/211207196-623a2f76-f564-401f-b643-0dae081b9d94.png)
After rebooting the server, the head of already claimed plots spawns in the hologram. New plots are unaffected.

2023-01-08 16:15 UTC, PierreSchwang commented
> ![Screenshot 2023-01-08 at 17 13 51](https://user-images.githubusercontent.com/13383509/211207196-623a2f76-f564-401f-b643-0dae081b9d94.png) After rebooting the server, the head of already claimed plots spawns in the hologram. New plots are unaffected.

Using DecentHolograms or HolographicDisplays?

2023-01-08 16:15 UTC, NotMyFault commented
DecentHolograms

2023-01-13 21:08 UTC, PierreSchwang commented
For now blocked by https://github.com/DecentSoftware-eu/DecentHolograms/issues/105

2023-11-15 15:00 UTC, PierreSchwang commented
> For now blocked by https://github.com/DecentSoftware-eu/DecentHolograms/issues/105

Was closed as fixed. Haven't tested yet.

2023-12-31 13:34 UTC, PierreSchwang commented
Absolute pita to rebase -> #168

2023-12-31 13:34 UTC, closed without merging